name: Terraform Test
on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - feature/#2_add_ci
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        run: terraform fmt
        continue-on-error: true

      - name: terraform validate
        run: terraform validate -no-color
        continue-on-error: true
